### PR TITLE
grid background

### PR DESCRIPTION
**Pull request by matthieujournault**
Proposal for addition of a grid background. 

The grid has 18 lines (thus imposing cell height), the width of cells is adjusted so that : 
- there is an even number of columns (board line split does not break a cell in two)
- cells are as square as can be but no gap on left or right.

### CODE REVIEW

**Comment by francoisschwarzentruber** [comment]
Dear Matthieu,
thank you for your nice contribution. Having a grid for the background is a useful and great idea. I will incorporate this feature this week-end. I have some questions:
- why 18 lines?
- what about choosing the number of lines/columns?
- what is your use of a grid? I could imagine several uses: write like in a notebook, play go, chess, geometry, etc.
- what about magnets that are grids?
Have a nice day.

**Comment by matthieujournault** [comment]
I use grid when teaching for several reasons : 
- to ensure that the text I write is not going up or down;
- since the addition of geometric shape I use grid to build shapes that have the same sizes (i draw circles using their bounding box and drag from a grid intersection to another one);
- When drawing a graph in an (x, y) graph, I place points on grid intersections for students to better read coordinates by following 
lines.
For all these reasons It felt OK and not too invasive (for me anyway) that the grid always be there (by opposition to having grid magnets added when needed).
18 was chosen because it feels like a good number of writing lines on my screen. This could obviously me made parametric (user chosen), however I think that having a background grid, one click away (without having to chose parameters) is a good thing.

**Comment by francoisschwarzentruber** [comment]
Thank you for your answer. I think I really like your contribution. By reading your answer, I now understand that the main usage is for writing like in a notebook and for geometry. I will accept your pull request soon. I now think having parametric grids is a bad idea:
- the background menu will just be overcomplicated
- nobody will use it
- users will feel comfortable by using the "standard" grid of tableaunoir and that's it!

**Comment by francoisschwarzentruber** [comment]
Dear Matthieu,
your answer convinced me to "keep it simple, stupid" (KISS). I really like your first commit, and I think it also works by sharing boards. :+1: 
However, you convinced me that parameterized grid is not so useful and makes the interface more complicated. Also, I am not sure it will work by sharing boards because the users may not have the same option values for the nb of lines and columns.

I suggest you to cancel the second commit. What do you think? What is your opinion?

**Comment by matthieujournault** [comment]
Did not think (at all) about sharing, will revert.

**Comment by francoisschwarzentruber** [comment]
I love your grid background. :+1: Thank you so much! Have a nice week-end!

**Pull request merged**
