### PR TITLE
Add build system

### PR DESCRIPTION
**Pull request by morandat**
Uses npm as buildsystem (via run build, lint, serve)
Uses webpack to producess assets
Fixes (most of) typescript imports
Extract share configuration to config.json
Add basic github action workflow

### CODE REVIEW

**Comment by morandat** [comment]
classic workflow may be :
```
npm ci # remove all node_modules and install back again
npm run build # Build everything to dist
npm run lint # See linter werning/errors (there are plenty)
npm run serve  # starts a local node server
```

**Comment by francoisschwarzentruber** [comment]
Hello,

thank you for your work. I ran

npm ci # remove all node_modules and install back again
npm run build # Build everything to dist
npm run lint # See linter werning/errors (there are plenty)
npm run serve  # starts a local node server

For the last command, I got:

> @ serve /home/fschwarz/tableaunoirtest/tableaunoir
> node server/main.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/fschwarz/tableaunoirtest/tableaunoir/server/main.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ serve: `node server/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fschwarz/.npm/_logs/2020-11-13T18_46_35_264Z-debug.log



Do you know how we may proceed? Maybe add "ws" in package.json?

**Comment by morandat** [comment]
true !
one line is missing in my post
npm --prefix server ci # clean and install dependency for server

**Comment by francoisschwarzentruber** [comment]
It works now. Thank you for your work!

**Pull request merged**
