### PR TITLE
Improved Spanish translation

### PR DESCRIPTION
**Pull request by JulioLoayzaM**
This should fix the Spanish version button not working, and I integrated @Kerl13 's suggestions to improve the translation's consistency (second person instead of third person, and pizarra instead of other variants).
Also, the file's content was duplicated so I deleted those lines.

### CODE REVIEW

**Comment by Kerl13** [comment]
Hi @JulioLoayzaM, thanks for the Spanish improvements! I was not 100% sure about my suggestions so it's good you had a second look :+1:

I have one question though. You wrote "por favor utilice …" in some place. It's the 3rd person right? Is it a mistake or do you think it sounds better like this?

**Comment by JulioLoayzaM** [comment]
Hi @Kerl13 !

No, you're right, I missed that one! Do you know what is the easiest way to correct it ?

**Comment by Kerl13** [comment]
I think it's fine to make another commit

**Comment by JulioLoayzaM** [comment]
Thanks!

**Comment by francoisschwarzentruber** [comment]
Really thank you for your work. Thank you Julio and thank you Martin.

**Pull request merged**
