### PR TITLE
Esbuild

### PR DESCRIPTION
**Pull request by Bluebottel**
Webpack is very slow compared to esbuild so I've replaced it and upgraded the developer experience a bit in the process.

* Build time used to be about 30s and is now near instant (~250ms)
* Bundle size from 5mb => 1.2mb
* Watch and serve mode added
* Npm scripts added for the new building process and Electron
* Cleaned up dependencies

Use `npm run esbuild-watch` to completely build the project and also start the web server on port 8000 (picks another port if not available). Watch mode automatically includes the source map so your workflow should be unaffected.

`npm run build` builds the project minified and without source map so automatic build processes should be unaffected.

Note that simply opening `index.html` and using the `file:///` protocol no longer works since `tableanoir.js` now has `type="module"`. Any web server will work as long as it gets the MIME types right.

### CODE REVIEW

**Comment by francoisschwarzentruber** [comment]
Thank you for your work! That is great. I have just one concern. I feel fear that `type="module"` and `es6` are not supported by all the browsers. I remember that Tableaunoir did not work on iPad, and that the solution was to compile to `es5`.
What do you think?

**Comment by Bluebottel** [comment]
I checked the browser support for ES6 features and it looks like it covers the vast majority of all browsers in current use. [This site](https://caniuse.com/es6) is my source. However I agree that you have a solid point about, potentially, old and not updated hardware that is essentially only used as a drawing tablet.

They *should* work anyway since any missing ES6 functionality gets polyfilled i.e. replaced by an identical version with backwards compatibility with this line:

`<script src="https://polyfill.io/v3/polyfill.min.js?features=es6">`

But it might not work properly. Do you have access to an older tablet to try the build out? In case it doesn't work there's a chance adding `&flags=always` might correct it like so: `<script src="https://polyfill.io/v3/polyfill.min.js?features=es6&flags=always">`.

**Comment by francoisschwarzentruber** [comment]
Hello @Bluebottel, I think I agree with you. 
I unfortunately do not have access to older tablet and to iPads etc. :(
At some point, I will merge this pull request. The thing is that I am terribly busy these months, sorry to be so slow.

**Comment by Bluebottel** [comment]
Hi!

My sincerest apologies, I did not mean to rush! I think you made a very valid point about compatibility with older devices and after some investigation the polyfill include has been there for quite a while which implies that it doesn't fully cover older browsers/devices.

My idea was to abort this PR, make a new build process using SWC for transpiling from typescript as well downgrading to pre-ES6 and finish with bundling with ESbuild. By the looks of it this should solve the problem completely.

I've managed to get a hold of an old iPad for testing but I haven't gotten around to do any experimentation yet. I can report back once it's done. The iPad is from 2016 I believe which should be old enough to be a decent stand in for old devices in general.

**Comment by francoisschwarzentruber** [comment]
Do not apologize at all! On the contrary, thank you! The compilation time is really too slow. Thank you for testing Tableaunoir on an iPad etc.

**Pull request closed without merging**
