### PR TITLE
Fix Github Actions

### PR DESCRIPTION
**Pull request by Vinetos**
This PR fix the auto deploy github actions file and reformat other files

### CODE REVIEW

**Comment by Vinetos** [comment]
I saw that `main.yml` and `deploy.yml` are manually disabled on github Actions, maybe you want to remove these file ?

**Comment by francoisschwarzentruber** [comment]
Thank you!
Concerning `mail.yml `and `deploy.ml`, I will see what to do this files later on. They are attempts for automatically making a release to be downloaded.

**Comment by francoisschwarzentruber** [comment]
Now it says `The process '/usr/bin/git' failed with exit code 128`.

**Comment by Vinetos** [comment]
After multipes tests and tries. This problem is because the default branch is now `main` and no more master. I think this is what broke the script. I'm searching for a fix

**Comment by Vinetos** [comment]
@francoisschwarzentruber Ok, found a fix : just change `BRANCH: master` to `BRANCH: main` and everything should be working

**Comment by francoisschwarzentruber** [comment]
Dear Vinetos,

thank you, I changed it, but there are still problems. I actually do not understand properly how github actions work.
What should we do to fix it?

Thank you!

**Comment by Vinetos** [comment]
@francoisschwarzentruber Have a look to my answer in #39

**Pull request merged**
